config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'products#index'
  
  resources :products, :order_items
  resource :cart, only: [:show]
  resources :users
  resources :orders

  get '/signup', to: "users#new"
  post '/signup', to: "users#create"

  get '/login_page', to: "auth#signin"
  post '/login_page', to: "auth#verify"

  get '/logout', to: "auth#logout" 

  get '/cart/:id', to: "order_items#destroy", as: "delete_item"
  get '/cart/:id', to: "order_items#create", as: "create_order"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :update_total
    before_create :update_status
  
    def calculate_total
      self.order_items.collect { |item| item.product.price * item.quantity }.sum
    end
  
    private
  
    def update_status
      if self.status == nil?
        self.status = "In progress"
      end
    end
  
    def update_total
      self.total_price = calculate_total
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :product

    validates :quantity, :presence => true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/temperature.rb
class Temperature < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :temperatures

    validates :username, presence: true
    validates :zip_code, presence: true
    validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :logged_in?
    helper_method :current_order

  def logged_in?
    !!session[:user_id]
  end

  def redirect_user
    if !logged_in?
      redirect_to login_page_path
    end
  end
  
    def current_order
      if session[:order_id]
        Order.find(session[:order_id])
      else
        Order.new
      end
    end

end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
    def signin
    end
  
    def verify
      # byebug
      # the username the teacher entered in the form
      @user = User.find_by(username: params[:auth][:username])
      if @user
        session[:user_id] = @user.id
        redirect_to products_path
      else
        flash[:message] = "Incorrect Info, please try again."
        render :signin
      end
    end
  
    def logout
      session.clear
      redirect_to login_page_path
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
    if Temperature.last.temp < 280
      render :show, layout: 'cold'
      @home_page_cold = true
    else
      @home_page_warm = true
    end
  end
  
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
      system "rake reseed"
         @products = Product.all
        @order_item = current_order.order_items.new
        if Temperature.last.temp < 280
          @products = Product.where(:weather_type => 'Cold')
          render :index, layout: 'cold'
          @home_page_cold = true
        else
          @products = Product.where(:weather_type => 'Warm')
          @home_page_warm = true
        end
      end

      def new
        @product = Product.new
      end
    
      def show
        @product = Product.find(params[:id])
      end
    
      def create
        @product = Product.new
        @product.name = params[:product][:name]
        @product.price = params[:product][:price]
        @product.weather_type = params[:product][:weather_type]
        @product.image_name = params[:product][:image_name]
        @product.save
        redirect_to product_path(@product)
      end
    
      def edit
        @product = Product.find(params[:id])
      end
    
      def update
        product = Product.find(params[:id])
        product.update(name: params[:product][:name], price: params[:product][:price])
        redirect_to "/product/#{product.id}"
      end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # before_action :redirect_user

    def index
          @user = User.all
    end
  
    def show
          @user = User.find_by(id: params[:id])
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
  
      if @user.save
       redirect_to user_path(@user)
      else
        flash[:message] = "Incorrect Info, please try again."
        render :new
      end
  
    end
  
    private
    def user_params
      params.require(:user).permit(:username, :zip_code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/temperatures_helper.rb
module TemperaturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/edit.html.erb
<h1>Edit Products</h1>
<%= form_for @product do |f| %>
    Name: <%= f.text_field :name %><br />
    Price : <%= f.number_field :price %><br />
    <%= f.submit %>
  <% end %>

app/views/products/index.html.erb
<div id="productBox">
<% @products.each do |product| %>
  <%= image_tag product.image_name %><br>
    <p><%= product.name %> | <%= number_to_currency product.price %><br>
   Weather Type: <%= product.weather_type %><br>
    <%= form_for @order_item do |f| %>
      <%= f.hidden_field :product_id, value: product.id %>
      Enter Quantity:<%= f.number_field :quantity %>
      <%= f.submit "Add to cart" %>
    <% end %></p>
  <% end %>
  </div>

  <ul id="cartForm">
  <%= link_to "Cart", cart_path%>
  </ul>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= form_for @product do |f| %>
    Name: <%= f.text_field :name %><br />
    Price : <%= f.number_field :price %><br />
    Weather Type : <%= f.text_field :weather_type %><br />
    Image Name : <%= f.text_field :image_name %><br />
    <%= f.submit %>
  <% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<%= @product.price %><br>

app/views/users/index.html.erb
<h1>All Users</h1>

<div class= 'ui huge middle aligned selection divided list'>
  <% @user.each do |user| %>
    <div class="item">
      <%= link_to user.username, users_path(user) %>
      <%= button_to "Return to Products Page", products_path, method: :get %><br>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Create a User</h1>
<%= flash[:message] %>
<%= form_for @user, html: {class: 'ui form'} do |f| %>
  <div class="field">
    <%= f.text_field(:username, placeholder: 'Enter your username...') %>
  </div>
  <div class="field">
    <%= f.text_field :zip_code, placeholder: 'Enter your Zip Code...' %>
  </div>
  <%= f.submit({class: 'ui huge pink button'}) %><br>
  <br>
  <%= button_to "Return to Products Page", products_path, method: :get %><br>
<% end %>

app/views/users/show.html.erb
  
<div class='ui raised segment'>
<div class='ui fluid card'>
  <div class='huge content'>
  <h1><%= @user.username %></h1><br>
  <h1><%= @user.zip_code %></h1><br>
  <%= button_to "Return to Products Page", products_path, method: :get %><br>
    <div class="description">
    </div>
  </div>
</div>
</div>