config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'products#index'
  
  resources :products, :order_items
  resource :cart, only: [:show]
  resources :users
  resources :orders

  get '/signup', to: "users#new"
  post '/signup', to: "users#create"

  get '/login_page', to: "auth#signin"
  post '/login_page', to: "auth#verify"

  get '/logout', to: "auth#logout" 

  get '/cart/:id', to: "order_items#destroy", as: "delete_item"
  get '/cart/:id', to: "order_items#create", as: "create_order"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :update_total
    before_create :update_status
  
    def calculate_total
      self.order_items.collect { |item| item.product.price * item.quantity }.sum
    end
  
    private
  
    def update_status
      if self.status == nil?
        self.status = "In progress"
      end
    end
  
    def update_total
      self.total_price = calculate_total
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :product

    validates :quantity, :presence => true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/temperature.rb
class Temperature < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :temperatures

    validates :username, presence: true
    validates :zip_code, presence: true
    validates :username, uniqueness: true
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
    def signin
    end
  
    def verify
      # byebug
      # the username the teacher entered in the form
      @user = User.find_by(username: params[:auth][:username])
      if @user
        session[:user_id] = @user.id
        redirect_to products_path
      else
        flash[:message] = "Incorrect Info, please try again."
        render :signin
      end
    end
  
    def logout
      session.clear
      redirect_to login_page_path
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
    if Temperature.last.temp < 280
      render :show, layout: 'cold'
      @home_page_cold = true
    else
      @home_page_warm = true
    end
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # before_action :redirect_user

    def index
          @user = User.all
    end
  
    def show
          @user = User.find_by(id: params[:id])
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
  
      if @user.save
       redirect_to user_path(@user)
      else
        flash[:message] = "Incorrect Info, please try again."
        render :new
      end
  
    end
  
    private
    def user_params
      params.require(:user).permit(:username, :zip_code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/temperatures_helper.rb
module TemperaturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Weather E-Commerce</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="ui teal inverted menu">
      <h1>Weather E-Commerce Hot</h1>
    <style>
</style>
      <div class="rightmenu">
        <% if !logged_in? %>
          <%= link_to 'Create a New User', new_user_path, {class: 'item'} %>
          <%= link_to "Login", login_page_path, {class: 'item'} %>
          <% else %>
          <%= link_to 'Create a New User', new_user_path, {class: 'item'} %>
          <%= link_to "Logout", logout_path, {class: 'item'} %>
        <% end %>
      </div>
  </div>
  <div class="ProductBar">
  <h3>Enjoy your Hot Products!</h3>
  </div>
  <body>
    <div class="ui centered grid ">
      <div class="eight wide column">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/cold.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather E-Commerce</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="ui teal inverted menu">
      <h1>Weather E-Commerce Cold</h1>
    <style>
</style>
      <div class="rightmenu">
      <% if !logged_in? %>
      <%= link_to 'Create a New User', new_user_path, {class: 'item'} %>
      <%= link_to "Login", login_page_path, {class: 'item'} %>
      <% else %>
      <%= link_to 'Create a New User', new_user_path, {class: 'item'} %>
      <%= link_to "Logout", logout_path, {class: 'item'} %>
    <% end %>
      </div>
  </div>
  <div class="ProductBar">
  <h3>Enjoy your Cold Products!</h3>
  </div>
  <body>
    <div class="ui centered grid ">
      <div class="eight wide column">
        <%= yield %>
      </div>
    </div>
  </body>
</html>